# Generated by Django 3.2.9 on 2021-11-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Novel_link', models.TextField(max_length=255)),
                ('Novel_Name', models.TextField(max_length=255)),
                ('Author_link', models.TextField(max_length=255)),
                ('Author_Name', models.TextField(max_length=255)),
                ('Country_link', models.TextField(max_length=255)),
                ('Country_Name', models.TextField(max_length=255)),
            ],
        ),
    ]
