# Generated by Django 3.2.9 on 2021-11-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='novel',
            new_name='novel_auth',
        ),
    ]
